#!/usr/bin/env python3
with open('C:\\Users\\DELL\\Documents\\dukadesk-website\\src\\styles.css', 'a', encoding='utf-8') as f:
    f.write('\n/* ── Footer CTA (global, works across themes) ── */\n')
    f.write('.footer-cta {\n')
    f.write('  padding: clamp(32px, 6vw, 56px) clamp(24px, 4vw, 48px);\n')
    f.write('  text-align: center;\n')
    f.write('  margin-bottom: clamp(32px, 5vw, 48);\n')
    f.write('}\n')
    f.write('\n.footer-cta h2 {\n')
    f.write('  font-family: sora;\n')
    f.write('  font-weight: 800;\n')
    f.write('  font-size: clamp(36px, 6vw, 48);\n')
    f.write('  color: #1A1A2E;\n')
    f.write('  margin-bottom: 16;\n')
    f.write('}\n')
    f.write('\n.footer-cta button {\n')
    f.write('  border: none;\n')
    f.write('  border-radius: 28;\n')
    f.write('  padding: clamp(14px, 3vw, 20px) clamp(32px, 5vw, 40px);\n')
    f.write('  font-size: clamp(14px, 3vw, 16);\n')
    f.write('  font-weight: 700;\n')
    f.write('  cursor: pointer;\n')
    f.write('  font-family: sora;\n')
    f.write('  background: #F4A026;\n')
    f.write('  color: #ffffff;\n')
    f.write('}\n')